version: '3.7'
services:
  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass redis --appendonly yes
    volumes:
      - .docker/redis:/var/lib/postgresql/data
    ports:
      - 6379:6379
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: local
    volumes:
      - ./docker/mysql:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 300s
      interval: 10s
      retries: 10
    networks:
      - server

  php8.0:
    container_name: php8
    build:
      context: .docker/php/php8.0
    restart: always
    ports:
      - "9080:9000"
    volumes:
      - "./html:/var/www/html"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - server

  nginx:
    container_name: nginx
    build:
      context: .docker/nginx
    volumes:
      - "./html:/var/www/html"
    ports:
      - "80:80"
    restart: always
    working_dir: /var/www/html
    networks:
      - server

networks:
  server:
    driver: bridge